application:
  port: 8000
  host: 0.0.0.0
  debug: True
  token_exp_minutes: 30
  jwt_secret_key: "8837fccb8a19b9a6e942bee4ccc78c6c9791c60f21ee1391219c9d233af763bb"
  jwt_algorithm: "HS256"
  ssl_cert: "./api/src/certs/cert.pem"
  ssl_key: "./api/src/certs/key.pem"
database:
  dsn: "mariadb+mariadbconnector://user:password@db:3306/mydatabase"
