services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  api:
    build:
        context: ./api/
    depends_on:
      - db
    ports:
      - 8000:8000

  web:
    environment:
      REACT_APP_API_URL: "https://0.0.0.0:8000"
      SSL_CRT_FILE: "./certs/cert.pem"
      SSL_KEY_FILE: "./certs/key.pem"
    build:
      context: ./web/
    ports:
      - 443:3000
    depends_on:
      - api
      - db
    stdin_open: true
